version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit_risk_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./mlruns:/app/mlruns
    environment:
      - MODEL_PATH=models:/credit_risk_model/Production
      - IS_DOCKER=true
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: credit_risk_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - IS_DOCKER=true
    depends_on:
      - api
    restart: unless-stopped
